schema:
  - "http://20.2.91.78/graphql"
documents:
  - "./src/**/*.ts"
generates:
  ./src/graphql/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
