schema:
  - "http://192.168.22.163:4000/graphql"
documents:
  - "./src/**/*.ts"
generates:
  ./src/graphql/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
