schema:
  - "https://dusgal.tsolmon.hackum.com/graphql"
documents:
  - "./src/**/*.ts"
generates:
  ./src/graphql/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
